#define IDI_ICON 1

char IconPNG[] = "\x89PNG\r\n\x1A\n\x00\x00\x00\rIHDR"
                "\x00\x00\x00 \x00\x00\x00 \b\x06\x00\x00\x00szz"
                "\xF4\x00\x00\x00\tpHYs\x00\x00\v\x13\x00\x00\v"
                "\x13\x01\x00\x9A\x9C\x18\x00\x00" "9\xECiTXtXM"
                "L:com.adobe.xmp\x00"
                "\x00\x00\x00\x00<\?xpacket be"
                "gin=\"\xEF\xBB\xBF\" id=\"W5"
                "M0MpCehiHzreSzNT"
                "czkc9d\"\?>\n<x:xmp"
                "meta xmlns:x=\"ad"
                "obe:ns:meta/\" x:"
                "xmptk=\"Adobe XMP"
                " Core 5.5-c021 7"
                "9.155772, 2014/0"
                "1/13-19:44:00   "
                "     \">\n   <rdf:"
                "RDF xmlns:rdf=\"h"
                "ttp://www.w3.org"
                "/1999/02/22-rdf-"
                "syntax-ns#\">\n   "
                "   <rdf:Descript"
                "ion rdf:about=\"\""
                "\n            xml"
                "ns:xmp=\"http://n"
                "s.adobe.com/xap/"
                "1.0/\"\n          "
                "  xmlns:dc=\"http"
                "://purl.org/dc/e"
                "lements/1.1/\"\n  "
                "          xmlns:"
                "photoshop=\"http:"
                "//ns.adobe.com/p"
                "hotoshop/1.0/\"\n "
                "           xmlns"
                ":xmpMM=\"http://n"
                "s.adobe.com/xap/"
                "1.0/mm/\"\n       "
                "     xmlns:stEvt"
                "=\"http://ns.adob"
                "e.com/xap/1.0/sT"
                "ype/ResourceEven"
                "t#\"\n            "
                "xmlns:tiff=\"http"
                "://ns.adobe.com/"
                "tiff/1.0/\"\n     "
                "       xmlns:exi"
                "f=\"http://ns.ado"
                "be.com/exif/1.0/"
                "\">\n         <xmp"
                ":CreatorTool>Ado"
                "be Photoshop CC "
                "2014 (Windows)</"
                "xmp:CreatorTool>"
                "\n         <xmp:C"
                "reateDate>2015-0"
                "3-18T00:10:30+01"
                ":00</xmp:CreateD"
                "ate>\n         <x"
                "mp:ModifyDate>20"
                "15-03-18T00:16:4"
                "0+01:00</xmp:Mod"
                "ifyDate>\n       "
                "  <xmp:MetadataD"
                "ate>2015-03-18T0"
                "0:16:40+01:00</x"
                "mp:MetadataDate>"
                "\n         <dc:fo"
                "rmat>image/png</"
                "dc:format>\n     "
                "    <photoshop:C"
                "olorMode>3</phot"
                "oshop:ColorMode>"
                "\n         <xmpMM"
                ":InstanceID>xmp."
                "iid:e3a1f254-afb"
                "0-d44f-a50d-5bbf"
                "5ce223d0</xmpMM:"
                "InstanceID>\n    "
                "     <xmpMM:Docu"
                "mentID>adobe:doc"
                "id:photoshop:9c1"
                "8588a-ccfb-11e4-"
                "bd43-9f41c9aae3d"
                "8</xmpMM:Documen"
                "tID>\n         <x"
                "mpMM:OriginalDoc"
                "umentID>xmp.did:"
                "b8e484f9-7db1-bc"
                "47-b91f-bb2270a7"
                "6531</xmpMM:Orig"
                "inalDocumentID>\n"
                "         <xmpMM:"
                "History>\n       "
                "     <rdf:Seq>\n "
                "              <r"
                "df:li rdf:parseT"
                "ype=\"Resource\">\n"
                "                "
                "  <stEvt:action>"
                "created</stEvt:a"
                "ction>\n         "
                "         <stEvt:"
                "instanceID>xmp.i"
                "id:b8e484f9-7db1"
                "-bc47-b91f-bb227"
                "0a76531</stEvt:i"
                "nstanceID>\n     "
                "             <st"
                "Evt:when>2015-03"
                "-18T00:10:30+01:"
                "00</stEvt:when>\n"
                "                "
                "  <stEvt:softwar"
                "eAgent>Adobe Pho"
                "toshop CC 2014 ("
                "Windows)</stEvt:"
                "softwareAgent>\n "
                "              </"
                "rdf:li>\n        "
                "       <rdf:li r"
                "df:parseType=\"Re"
                "source\">\n       "
                "           <stEv"
                "t:action>saved</"
                "stEvt:action>\n  "
                "                "
                "<stEvt:instanceI"
                "D>xmp.iid:e3a1f2"
                "54-afb0-d44f-a50"
                "d-5bbf5ce223d0</"
                "stEvt:instanceID"
                ">\n              "
                "    <stEvt:when>"
                "2015-03-18T00:16"
                ":40+01:00</stEvt"
                ":when>\n         "
                "         <stEvt:"
                "softwareAgent>Ad"
                "obe Photoshop CC"
                " 2014 (Windows)<"
                "/stEvt:softwareA"
                "gent>\n          "
                "        <stEvt:c"
                "hanged>/</stEvt:"
                "changed>\n       "
                "        </rdf:li"
                ">\n            </"
                "rdf:Seq>\n       "
                "  </xmpMM:Histor"
                "y>\n         <tif"
                "f:Orientation>1<"
                "/tiff:Orientatio"
                "n>\n         <tif"
                "f:XResolution>72"
                "0000/10000</tiff"
                ":XResolution>\n  "
                "       <tiff:YRe"
                "solution>720000/"
                "10000</tiff:YRes"
                "olution>\n       "
                "  <tiff:Resoluti"
                "onUnit>2</tiff:R"
                "esolutionUnit>\n "
                "        <exif:Co"
                "lorSpace>65535</"
                "exif:ColorSpace>"
                "\n         <exif:"
                "PixelXDimension>"
                "32</exif:PixelXD"
                "imension>\n      "
                "   <exif:PixelYD"
                "imension>32</exi"
                "f:PixelYDimensio"
                "n>\n      </rdf:D"
                "escription>\n   <"
                "/rdf:RDF>\n</x:xm"
                "pmeta>\n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "                "
                "                "
                "                "
                "                "
                "              \n "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "   \n            "
                "                "
                "                "
                "                "
                "                "
                "                "
                "        \n       "
                "                "
                "                "
                "                "
                "                "
                "                "
                "             \n  "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "  \n             "
                "                "
                "                "
                "                "
                "                "
                "                "
                "       \n        "
                "                "
                "                "
                "                "
                "                "
                "                "
                "            \n   "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                " \n              "
                "                "
                "                "
                "                "
                "                "
                "                "
                "      \n         "
                "                "
                "                "
                "                "
                "                "
                "                "
                "           \n    "
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "\n               "
                "                "
                "                "
                "                "
                "                "
                "                "
                "     \n          "
                "                "
                "                "
                "                "
                "                "
                "                "
                "          \n     "
                "                "
                "                "
                "                "
                "                "
                "                "
                "               \n"
                "                "
                "                "
                "                "
                "                "
                "                "
                "                "
                "    \n           "
                "                "
                "                "
                "                "
                "                "
                "                "
                "         \n      "
                "                "
                "      \n<\?xpacket"
                " end=\"w\"\?>\x03\xEB\xF5\xB5\x00\x00"
                "\x00 cHRM\x00\x00z%\x00\x00\x80\x83\x00\x00"
                "\xF9\xFF\x00\x00\x80\xE9\x00\x00u0\x00\x00\xEA`\x00\x00"
                ":\x98\x00\x00\x17o\x92_\xC5" "F\x00\x00\x05\xAAID"
                "ATx\xDA\xE4\x97Ml\x1B\xD7\x11\xC7\x7Fow\xF9"
                "!R\xA6%\xD2!-\xD3\x96\xCDH\xB4\x1C'q\xBF"
                "\xD0\xA0rZ\xC3\x86S\x03\xB5\xD2\x04uO\xEA\xADg"
                "\xF7R\xE7\x92\xDE\x9A\x00\xB9\x04\x89\x81\"\x85\x8A\x16="
                "\xD6h\x8B N\x91\xC4U\x8D\xA6u\x90:5R\xBB"
                "V\x05\xC9j#\x85\xB2-\xD3\nC\x91\x14\?\xB5\xDC"
                "\xCF\x97" "C\xB2\f\xA5\xE8\xFB\x92" "C\x1F\xB0\xC0\xEE\x90\xEF"
                "\xCD\xCC\x7F" "f\xFE" "3OH)\xF9" "2\x97\xC2\x97\xBC\xB4"
                "\x95\x82\x1B" "7n\xC8[\xB7n!\x84X&\x97R\xB6"
                "\x1E\xD7u\xF1\x90k\x97{2\xC7q8{\xF6\xAC\xD8"
                "\x8C\x01" "be\b.\\\xB8 \x87\x87\x87" "7\xDC\xB8r"
                "\x9F\xEB\xBA\x00" "d2\x19\xA6\xA6\xA6h4\x1A" "D\xA3Q"
                "\x86\x86\x86\xC4\x96\x10\xF0<\xC9" "f\xB3\xAD" "C\x15\xE5\xF3"
                "Hy\xEF+\x11j_\xC1`\x90\xC3\x87\x0F" "311"
                "\xC1\xC5\x8B\x17\xE5\x99" "3g\xC4\xA6s\xA0\xDD" "3EQ"
                "Z\n\xBDw!\xC4" "2\xE5\x9E\xDC{\xFC~\?\xBA\xAE"
                "\xD3\xD7\xD7G\x7F\x7F\?\x96" "eq\xE9\xD2%\xB9\xE5$"
                "\\\xE9\xF5Z\x8A\xD7" "B\xC0" "3&\x9DNS,\x16\xB7"
                "_\x05k)Y\xED\x7F\x8A\xA2\xA0\xEB:\xB1X\fU"
                "U9t\xE8\x10\xF1x\x9C\xBE\xBE>FFF\xE4\xA6"
                "s\xC0u]\x84\x10-\xCF\x1D\xC7\x01\xC0\xE7\xF3m\x98"
                "\v\xA5R\x89\xE9\xE9i&''\x01\xB0m\x1B\xC7q"
                "\xB0m\x9B\xF3\xE7\xCF\xCBs\xE7\xCE\x89u\r\xF0\x12\xAF"
                "\xFDp\xCF\x10\xEF" "7\xCB\xB2h6\x9B\xE8\xBA\x8Em\xDB"
                "H)QU\x15M\xD3H$\x12\xC4\xE3q\xAA\xD5*"
                "\xAE\xEB\xA2(\n\x9A\xA6\x11\b\x04\x18\x1D\x1D\xDD\x1C\x02"
                "\x9ERO\xA1\xAA\xAA-D\x1C\xC7\xA1\xB6T\xE5^\xF6"
                "\x0E\xB5" "b\x8ER\xB9\x86i4\xA9[\x1A\xFB\xE3\x0F\x90"
                "\xEA\x1F\xA0\xAB\xAB\x8B\x9E\x9E\x1E\xFC~\x7F\xCB\x89H$"
                "\xB2j\xE5h\x9B\x89\xAD\x10\x02)%\xA6i\xF2\xDF\x99"
                ")\x16g\xFFM\xE0\xA3)\xA2" "F\x95N\xC3" "D\xF5\xFB"
                "\x98m\xA8\xBC\xF7\xE1\x0E\xEE\xE7\?\xE6\xF1\xC1\xEF\xA0i"
                "\x1A\x91HdY\xD8" "6\x95\x03\xAB%\xA0\xAA\xAA(\x8A"
                "\xC2\xDBW.S\x99\x1D\xC3" "7\x97\xE7j\xB3\x97\x7F\xD5"
                "\x1E" "BU\x04\n\x06\xC7;2|\xAD\xE3" "6\xEF\x8D]"
                "\xC3\xEFS\xF9\xF6\xE3'\b\x87\xC3\xF8|\xBE\x96\xE7\xAB"
                "\xF5\x9D\rC\xE0y\?\x97\xBD\xC7\xCD\xFF\x8Cqt\xE9"
                "\x03~\x91\x1B" "f\xBE\x11" "F\xB5l\x1C\t\x9A\xDB\xE4\x0F"
                "\"\xCDP\x7F'\x83\x1Dop}r\x9C\xD4\x81" "4\xD1"
                "h\xB4U\x92[b\xC2\x95(h\x9A" "Fv\xFE>]"
                "\xC5\xFF" "1i\xA6(6\x17\x91\r\x1B\xCB.#\x9D\x06"
                "..\x81`'W\xE7\xA3\x1C\xE9M\xE3+\xE5(W"
                "\x16q\x1Cg\x19\x7Fl\t\x81\xF6\xDAn,-\xF1\xD7"
                "w\xAE\xF2\xA0\xDB S\x0FS/\v\xD4\xE6" "4\xB6\xDD"
                "\xC0" "2\nhj\a8\tt\xF1 \xAE\xA3\xE2\x18M"
                "\xD4\xCF\xBC\xDE\xA8\xDD+k\xF1@{):\x8E\xC3\xE2"
                "G\x19\x92\x81\x9D\xBC\xBBt\x84\x80[\xC3\xB6*\x18z"
                "\x1E" "CZ\xD4\xEA" "9\x96\xAA\xF7p\x8D\n\xB6" "ccZ"
                "&R~z\x96W=[F\xC0\x83N\b\x81\xDF\xE7"
                "\xC3um,\x1D\f3\x80k\x16\xD1+9\x14;\xCB"
                "\xC1H\x1D\xB9K\xA3\xA1\xDF" "a\xA1\xD9\x8B%5\x96L"
                "\x13\x00]\xD7" "1\f\x03UU7\x9F\x03\xED\xDE{\x06"
                "\xDD\x18\xBF\xCE\x0E\xAB@A&0\xEB%\xECz\x1E\xE4"
                "mN&\\\xD2]\x0F\xE0\xFA\xFCX\x8D\x8F\xB9x\xFB"
                "\n\xE5Z\x92n\x9A\\{\xFF]\x92\xC9}\x04\x83" "A"
                "\x02\x81\x00\xDBjF\x8A\xA2ps\xFC:7\xAF\xBC\xC1"
                "7\xBA\xC3\xFC\xAE\xF4\x04N\xF5.\xE8\x1Frj\x7F\x83"
                "Do\f\xFF\x89oQ\xDC\x19 z|\x90\xA7\x8E\x86"
                "x\xF5\xEE\x1E\xBEz\xF0\xEBh\v\xD3\xFCy\xF4u\x1A"
                "\x8D" "F\x8B\xCA\xB7\xD4\x8EUU\xE5\xAD\xCB\xA3\xDC\xBA\xF6"
                "6\a\x15\x9D\xD7*\xA7\xA9,\xD6" "0\x8A\xFF\xA4\xA3" "c"
                "\x8E;\v\x0E\xAF" "e\xB2" "D\xF6\xEE\xE6\xD1'\x9F\xE0\xBE"
                "\b0\xAE" "7qr\xD7\xF8\xE3\xDC\x00" "C\xBD\x9D\xE4r"
                "\xF3\x98\xA6\xB9\xAE\x01\xDAz\b\xFC\xFDo\x7F\xE1\x87\xBB"
                "\xEB\xBC\xAF\x7F\x93\\e'N\xE9U\x0E\xEC\xAFq\xEC"
                "\xF8\xF7(\x94M\x8E\xC4\x83\xBC" "3\xFE\x0F\x06\x02IB"
                "\x95y\x92\x8F\xED" "A\v\xE9\xD4\xAA%~\x9B\xDDK\xC8"
                "_n\xF1\xC8\xB6x\xE0\xD4\xC9\xEF\xF2\xD6\xE5\?a4"
                "\xAF\x12Q\a\xE8\x7Fl7O\x9D>\x8D\x94\x02\xDB\xB2"
                "\xB1,\x83\x87\xC5" "AD-\xCF\xC9\xC3\x03\xFC\xFEv\x9E"
                "cO\x9F@\xA8\x82\x99\xD9y\xE6\xA6kh\x9A\xB6\xB5"
                "$\xF4\fp]\x97\xEF\?\xF9\x03" "b\xB1\x18o\xBE\xF9"
                ":\x91\xBB" "c<20\xC8" "B\xBE@\xA1PB(\x82"
                "p\xB8\x93|\xBE\xC0\x9E=\t~5\x95go\xCF>"
                "f\xA6\? \x14\fa\xD5\xCA \x04\xA1P\bM\xD3"
                "\xB6>\x13:\x8E\x83\x94\x92\xA3\x83\xC7x\xE4\xE1\xAF\xF0"
                "\xF2\xCB/0>6\xC6\x8E\x1D\x11\x8C\xA6\x81iY\xA4"
                "\a\xD2\xE8\xA6\xCDLf\x9EP(@\xB5Z'33"
                "K\xB9\xB2H,\x1A\xE5G\xC3\?\xA6\xBB\xBB{\xDD\x86"
                "\xB4" "f\x19z\x84" "d\xDB" "6\x91\xC8N\x9E}\xF6\xE7\xFC"
                "\xFA" "7\xAFP\xADVh\x1AMr\xB9\x1CS\x93\x93\x1C"
                "8\x90\"\xDE\xB3\v\xC3\xB0\x98\x98\x98@\xD3T\x86\x86"
                "\x9E\xE6\xE4\x89S$\x12=\xAD" "9a[<\xD0nD"
                "(\x14\xE6\xDCO\x7F\x86\x94\x12" "EQ(\x16\v\xBC\xF2"
                "\xCB\x97XX\xC8S\xAB\xD5P\x84 \x99L\xF2\x93\xB3"
                "\xCF\xB0oo\xEF\xA6hx\xCD*Xm\xE6\xB7,k"
                "\xD9p\x1A\x8B\xED\xE2\xF9\xE7^\xFC\xC2\xF4\xD4\xBE\xD7\xAB"
                "\x00\xD7u\xD7LDm\xAD\x12\x8C" "D\"\x1B\xDFj\xDA"
                "&\x9Cv\n\xF7z\x80\xF7\xBD\xDE]\xE2\v\x06\xA4R"
                ")FFF\xD6\x8D\xDBv\x96m\xDB\xA4R\xA9\x8D\xAF"
                "f\xFFw\xB7\xE3O\x06\x00\x1CI\xE8=\xC5\x03\x9E\xE6"
                "\x00\x00\x00\x00IEND\xAE" "B`\x82";
